import type { Metadata } from 'next';
//import { Inter } from 'next/font/google';
// import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import ProviderSession from './ProviderSession';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ProviderSession>{children}</ProviderSession>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
