name: Deploy Gazelle
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 🚀 Deploy Gazelle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Gazelle
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'unnecessary'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_HOST_API_KEY: ${{ secrets.HOST_API_KEY }}
          envkey_HOST_API: ${{ vars.HOST_API }}
          envkey_GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          envkey_GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          envkey_NEXT_AUTH_SECRET: ${{ secrets.NEXT_AUTH_SECRET }}
          envkey_NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy with rsync
        run: rsync -aRvz --delete .env .next next-env.d.ts next.config.mjs package-lock.json package.json tsconfig.json public ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:gazelle

      - name: restart pm2
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_PORT }} '
            export PATH=$PATH:/home/nodejs/.nvm/versions/node/v22.14.0/bin
            source ~/.nvm/nvm.sh
            nvm use lts/jod
            npm install
            pm2 restart gazelle --update-env
          '
