name: Deploy Gazelle
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 🚀 Deploy Gazelle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Gazelle
        run: npm run build

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_HOST_API_KEY: ${{ secrets.HOST_API_KEY }}
          envkey_HOST_API: ${{ vars.HOST_API }}
          envkey_GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          envkey_GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          envkey_NEXT_AUTH_SECRET: ${{ secrets.NEXT_AUTH_SECRET }}
          envkey_NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rlgoDzvc -i --delete'
          SOURCE: '.next/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: 'gazelle'
          EXCLUDE: '/dist/, /node_modules/'
